var i = 0
childObjects[i++] = fallingChild_1
childObjects[i++] = fallingChild_2
childObjects[i++] = fallingChild_3
childObjects[i++] = fallingChild_4
childObjects[i++] = fallingChild_5
childObjects[i++] = fallingChild_6
childObjects[i++] = fallingChild_7
childObjects[i++] = fallingChild_8
childObjects[i++] = fallingChild_9
childObjects[i++] = fallingChild_10
childObjects[i++] = fallingChild_11
childObjects[i++] = fallingChild_12
childObjects[i++] = fallingChild_13
childObjects[i++] = fallingChild_14
childObjects[i++] = fallingChild_15
childObjects[i++] = fallingChild_16
childObjects[i++] = fallingChild_17
childObjects[i  ] = fallingChild_18

